### ISSUE TITLE
cool!

### ISSUE THREAD

**Issue by aquynh** [sidneyp/capstone-tricore#1]
oh this is so cool! do you want to send a pull request to include this into Capstone's next branch?

i am planning to release Capstone 4.0 soon based on the next branch. would be nice if this arch is included, and you can help to maintain it.

thanks

**Comment by sidneyp** [comment]
It will be a honour contribute to Capstone.
This is just the beginning and when I have something relevant, I send a pull request.
Thank you too!

**Comment by aquynh** [comment]
awesome, please keep me updated, thanks.

**Comment by sidneyp** [comment]
I need to work first in LLVM before start with Capstone for TriCore.
The TriCore backend in LLVM is missing some ".inc" files which are needed in Capstone.

**Comment by aquynh** [comment]
where did you get the LLVM backend of TriCore?

this is not surprise. typically, architectures supported by LLVM come with no disassembler. this is because disassembler is not essential for LLVM: it is only needed for debugging (LLDB), and is always treated as second class in LLVM framework.

**Comment by sidneyp** [comment]
I am still implementing it. 
It is one of my repositories here: [sidneyp/llvm-tricore](https://github.com/sidneyp/llvm-tricore)

**Comment by aquynh** [comment]
very cool! if you can also make assembler (AsmParser) for it, i may support TriCore in Keystone as well (http://keystone-engine.org).

any plans to push this to LLVM eventually?

**Comment by sidneyp** [comment]
I didn't have this plan, but I can push to LLVM what I do too.
I am glad to help!

**Comment by brandonros** [comment]
@aquynh Did Tricore support make it to Capstone?

**Comment by aquynh** [comment]
No.
